export const SET_SEARCH = "SET_SEARCH";
export const SET_SELECT_QUERY = "SET_SELECT_QUERY";
export const FETCH_JOBS = "FETCH_JOBS";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_ERROR = "FETCH_JOBS_ERROR";
